name: MSBuild

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  build-cad-4:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
  
    # Install .NET Framework Developer Packs
    - name: Install .NET Framework 4.6 Developer Pack
      run: |
        choco install netfx-4.6-devpack -y --no-progress

    - name: Install .NET Framework 4.7 Developer Pack
      run: |
        choco install netfx-4.7-devpack -y --no-progress
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
      
    - name: Restore Packages
      run: nuget restore RibbonXml.sln

    # Build .NET 4.6 project
    - name: Build .NET 4.6 (ACAD)
      run: msbuild References/AcadNet46/AcadNet46.csproj /t:Restore,Build /p:Configuration=Release

    # Build .NET 4.7 project (ZWCAD)
    - name: Build .NET 4.7 (ZCAD)
      run: msbuild References/ZcadNet47/ZcadNet47.csproj /t:Restore,Build /p:Configuration=Release /p:DefineConstants=ZWCAD

    # Build .NET 8.0 project
    - name: Build .NET 8.0 (ACAD) (Test 80)
      run: dotnet build References/AcadNet80/AcadNet80.csproj -c Release

    - name: Compress ZIP with all DLL
      run: |
        $OutputZip = "RibbonXml.zip"
        $Files = @(
            "References/AcadNet46/bin/Release/AcadNet46.dll",
            "References/ZcadNet47/bin/Release/ZcadNet47.dll",
            "References/AcadNet80/bin/Release/net8.0-windows8.0/AcadNet80.dll"
        )
        if (Test-Path $OutputZip) { Remove-Item $OutputZip }
        Compress-Archive -Path $Files -DestinationPath $OutputZip

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NET_DLL
        path: RibbonXml.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      if: github.ref == 'refs/heads/master'
      with:
        # Generate version string: YYYY.MM.run_number
        tag_name: v0.0.${{ github.run_number }}-alpha
        name: Release v0.0.${{ github.run_number }}-alpha
        draft: false
        prerelease: false
        files: RibbonXml.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
